name: ${project.name}
description: ${project.description}
website: ${project.url}
version: ${plugin.version}
authors: [${git.branch.authors}]
main: fr.mrcubee.waypoint.WayPointPlugin
api-version: 1.13
commands:
  gps:
    description: Enables and disables GPS.
    usage: |
      §7--------------------- [§a${project.name}§7] ---------------------
      §7- §a/gps stop §f- §7Disable GPS.
      §7- §a/gps <x> <z> §f- §7Enable GPS on the desired coordinate.
      §7- §a/gps <x> <z> <world> §f- §7Enable GPS on the desired coordinate.
      §7- §a/gps <x> <y> <z> &f- §7Enable GPS on the desired coordinate.
      §7- §a/gps <x> <y> <z> <world> §f- §7Enable GPS on the desired coordinate.
      §7- §a/gps waypoint <name> §f- §7Enable GPS on the desired waypoint.
      §7- §a/gps player <name> §f- §7Enable GPS on the desired player.
  waypoint:
    aliases: wp
    description: Manage waypoints.
    usage: |
      §7--------------------- [§a${project.name}§7] ---------------------
      §7- §a/waypoint create <name> §f- §7Create a waypoint at the current position.
      §7- §a/waypoint create <name> <x> <z> §f- §7Create a waypoint on the desired coordinates.
      §7- §a/waypoint create <name> <x> <z> <world> §f- §7Create a waypoint on the desired coordinates.
      §7- §a/waypoint create <name> <x> <y> <z> §f- §7Create a waypoint on the desired coordinates.
      §7- §a/waypoint create <name> <x> <y> <z> <world> §f- §7Create a waypoint on the desired coordinates.
      §7- §a/waypoint remove <name> §f- §7Delete a waypoint.