name: ${project.name}
description: "${project.description} Current version: ${plugin.version}"
website: ${project.url}
version: ${project.version}
authors: [${git.branch.authors}]
softdepend: [Skript]
main: fr.mrcubee.waypoint.WayPointPlugin
api-version: 1.13
commands:
  gps:
    permission: waypoint.gps.use
    description: Enables and disables GPS.
    usage: |
      §7--------------------- [§a${project.name}§7] ---------------------
      §7- §a/gps stop §f- §7Disable GPS.
      §7- §a/gps <x> <z> §f- §7Enable GPS on the desired coordinate.
      §7- §a/gps <x> <z> <world> §f- §7Enable GPS on the desired coordinate.
      §7- §a/gps <x> <y> <z> &f- §7Enable GPS on the desired coordinate.
      §7- §a/gps <x> <y> <z> <world> §f- §7Enable GPS on the desired coordinate.
      §7- §a/gps waypoint <name> §f- §7Enable GPS on the desired waypoint.
      §7- §a/gps player <name> §f- §7Enable GPS on the desired player.
  waypoint:
    permission: waypoint.waypoint.use
    aliases: wp
    description: Manage waypoints.
    usage: |
      §7--------------------- [§a${project.name}§7] ---------------------
      §7- §a/waypoint create <name> §f- §7Create a waypoint at the current position.
      §7- §a/waypoint create <name> <x> <z> §f- §7Create a waypoint on the desired coordinates.
      §7- §a/waypoint create <name> <x> <z> <world> §f- §7Create a waypoint on the desired coordinates.
      §7- §a/waypoint create <name> <x> <y> <z> §f- §7Create a waypoint on the desired coordinates.
      §7- §a/waypoint create <name> <x> <y> <z> <world> §f- §7Create a waypoint on the desired coordinates.
      §7- §a/waypoint remove <name> §f- §7Delete a waypoint.

permissions:
  waypoint.gps.use:
    description: Permission to use the GPS commands.
    default: true
  waypoint.gps.use.waypoint:
    description: Permission to use the GPS command to target waypoint.
    default: true
  waypoint.gps.use.player:
    description: Permission to use the GPS command to target player.
    default: true
  waypoint.gps.use.*:
    description: Permission to use all GPS subcommands.
    default: false
    children:
      waypoint.gps.use: true
      waypoint.gps.use.waypoint: true
      waypoint.gps.use.player: true
  waypoint.waypoint.use:
    description: Permission to use the Waypoint command.
    default: true
  waypoint.death-waypoint:
    description: Players with this permission will have a waypoint created at the location of their death.
    default: true
  waypoint.admin:
    default: false